In [1]:
import pybullet as pb
import time
import pybullet_data
import numpy as np
physicsClient = pb.connect(pb.GUI)#or p.DIRECT for non-graphical version
pb.setAdditionalSearchPath(pybullet_data.getDataPath()) #optionally
pb.setGravity(0,0,-10)
planeId = pb.loadURDF("plane.urdf")
startPos = [1.3,0.8,0.4]
startOrientation = pb.getQuaternionFromEuler([0,0,1.1])
# boxId = p.loadURDF("/home/haoluo/catkin_ws/src/quad-sdk/quad_simulator/spinebot_description/quad_spine_sdf/testSpinebot.urdf",startPos, startOrientation)
boxId = pb.loadURDF("/home/haoluo/catkin_ws/src/quad-sdk/quad_simulator/spirit_description/urdf/spirit.urdf",startPos, startOrientation)  
# boxId = p.loadSDF("/home/haoluo/catkin_ws2/src/quad-sdk/quad_simulator/spirit_description/sdf_mesh/spirit.sdf")  
#set the center of mass frame (loadURDF sets base link frame) startPos/Ornp.resetBasePositionAndOrientation(boxId, startPos, startOrientation)
nJoints = pb.getNumJoints(boxId)
jointNameToId ={}
for i in range (nJoints):
    jointInfo = pb.getJointInfo(boxId, i)
    jointNameToId[jointInfo[1].decode('UTF-8')] = jointInfo[0] 
    print(jointInfo[1].decode('UTF-8'))
# spine=jointNameToId["spine"]
abdfl=jointNameToId["8"]
hipfl=jointNameToId["0"]
kneefl=jointNameToId["1"]
abdfr=jointNameToId["9"]
hipfr=jointNameToId["2"]
kneefr=jointNameToId["3"]
abdbl=jointNameToId["10"]
hipbl=jointNameToId["4"]
kneebl=jointNameToId["5"]
abdbr=jointNameToId["11"]
hipbr=jointNameToId["6"]
kneebr=jointNameToId["7"]

legFR = [abdfr,hipfr,kneefr]
legFL = [abdfl,hipfl,kneefl]
legBR = [abdbr,hipbr,kneebr]
legBL = [abdbl,hipbl,kneebl]

jtoe = jointNameToId["jtoe3"]
print('jtoe3', jtoe)


toe_idx = 1


p_gain = 0.12

all_legs = [legFL,legBL,legFR,legBR]
leg_phase = [0,2,2,0]

# Stand_angs = [0.0,1.0,1.5]
Stand_angs = [0.0,0.8,1.5]
Walk_angs = [[0.0,0.7,1.5],[0.0,0.7,1.2],[0.0,1.0,1.2],[0.0,1.0,1.5]]

from robot import Robot_sensors
from robot import pos_quat_to_SE3, SE3_transform_pos

test = Robot_sensors(pb,boxId)


for i in range(5000):
    pb.stepSimulation()
    # p.setJointMotorControl2(boxId, jointIndex=spine,controlMode=p.POSITION_CONTROL,targetPosition=0.0,positionGain=p_gain) 
    for k,j in zip(all_legs,leg_phase):
        pb.setJointMotorControl2(boxId, jointIndex=k[0],controlMode=pb.POSITION_CONTROL,targetPosition=Stand_angs[0],positionGain=p_gain)
        pb.setJointMotorControl2(boxId, jointIndex=k[1],controlMode=pb.POSITION_CONTROL,targetPosition=Stand_angs[1],positionGain=p_gain)
        pb.setJointMotorControl2(boxId, jointIndex=k[2],controlMode=pb.POSITION_CONTROL,targetPosition=Stand_angs[2],positionGain=p_gain)
#         print(test.read_contact(toe_idx),'contact')
#         print(test.read_contact_state(),'contact')
#         print(test.read_contact(toe_idx),'contact\n')
#     toe_contact = test.read_single_contact(toe_idx)
    toe_contact = test.read_all_contacts_pts_body()
    if i%200 ==0:
        print(i)
        print(toe_contact[0],'pos\n')
        print(toe_contact[1],'grf\n')
        print('posvec\n')
pb.disconnect()

pybullet build time: May 20 2022 19:44:17


8
0
1
jtoe0
9
2
3
jtoe1
10
4
5
jtoe2
11
6
7
jtoe3
cmu_text_right
cmu_text_left
jtoe3 15
[3, 7, 11, 15]
0
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] pos

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] grf

posvec

200
[[ 0.24105432  0.17097189 -0.29900953]
 [-0.21066717  0.17109054 -0.2980146 ]
 [ 0.24101628 -0.17102564 -0.29907593]
 [-0.21069428 -0.17092248 -0.29808102]] pos

[[ -3.54620281   5.21498487 -29.69024132]
 [ -6.12633948  -0.87413553 -36.8208962 ]
 [  4.1088744    1.95557018 -29.59743955]
 [  5.5638788   -6.29565204 -36.89327341]] grf

posvec

400
[[ 0.24106654  0.17095631 -0.2990072 ]
 [-0.21065494  0.17110822 -0.29801293]
 [ 0.24100331 -0.17104122 -0.29907809]
 [-0.21070725 -0.17090479 -0.29808385]] pos

[[ -4.08642399   5.2789002  -29.74561161]
 [ -5.81279311  -1.26913603 -36.76471939]
 [  3.73607391   2.30846847 -29.54175461]
 [  6.16314577  -6.31823871 -36.94991589]] grf

posvec

600
[[ 0.24108159  0.1709371  -0.29900432]
 [-0.21063988  0.17113001 -0.29801087]
 

In [2]:
[[ 0.2403745   0.17093127 -0.29916018]
 [-0.21043732  0.17103387 -0.29801058]
 [ 0.24029436 -0.17104613 -0.29910064]
 [-0.20969449 -0.17095399 -0.29795314]]

SyntaxError: invalid syntax (1400169908.py, line 1)

In [ ]:
from robot import SE3_transform_pos

In [ ]:
testpair = [[1,3,3],[0,0.1,0.3,1.2]]
testvec = [0,1,1]
pos_quat_to_SE3(testpair[0],testpair[1])

In [ ]:
SE3_transform_pos(testvec,testpair[0],testpair[1])